/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export interface Category {
  'categoryId' : CategoryId,
  'name' : string,
  'description' : string,
}
export type CategoryId = bigint;
export interface CustomerDetails {
  'city' : string,
  'name' : string,
  'state' : string,
  'address' : string,
  'pinCode' : string,
  'phone' : string,
}
export interface Order {
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'orderId' : OrderId,
  'cartItems' : Array<CartItem>,
  'totalAmount' : bigint,
  'customerDetails' : CustomerDetails,
}
export type OrderId = bigint;
export type PaymentMethod = { 'upi' : { 'upiId' : string } } |
  { 'cashOnDelivery' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'failed' : null };
export interface Product {
  'categoryId' : CategoryId,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'productId' : ProductId,
  'imageUrl' : [] | [string],
  'price' : bigint,
}
export type ProductId = bigint;
export interface UserProfile {
  'city' : [] | [string],
  'name' : string,
  'state' : [] | [string],
  'address' : [] | [string],
  'pinCode' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string, string], undefined>,
  'addProduct' : ActorMethod<
    [string, bigint, string, [] | [string], CategoryId, boolean],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[CategoryId], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markOrderAsPaid' : ActorMethod<[OrderId], undefined>,
  'placeOrder' : ActorMethod<
    [Array<CartItem>, CustomerDetails, PaymentMethod],
    OrderId
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedDemoData' : ActorMethod<[], undefined>,
  'trackOrder' : ActorMethod<[OrderId, string], [] | [Order]>,
  'updateCategory' : ActorMethod<[CategoryId, string, string], undefined>,
  'updatePaymentStatus' : ActorMethod<[OrderId, PaymentStatus], undefined>,
  'updateProduct' : ActorMethod<
    [ProductId, string, bigint, string, [] | [string], CategoryId, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];