/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CategoryId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'failed' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Record({ 'upiId' : IDL.Text }),
  'cashOnDelivery' : IDL.Null,
});
export const OrderId = IDL.Nat;
export const ProductId = IDL.Nat;
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const CustomerDetails = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'pinCode' : IDL.Text,
  'phone' : IDL.Text,
});
export const Order = IDL.Record({
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'orderId' : OrderId,
  'cartItems' : IDL.Vec(CartItem),
  'totalAmount' : IDL.Nat,
  'customerDetails' : CustomerDetails,
});
export const Product = IDL.Record({
  'categoryId' : CategoryId,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'productId' : ProductId,
  'imageUrl' : IDL.Opt(IDL.Text),
  'price' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'city' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'state' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'pinCode' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const Category = IDL.Record({
  'categoryId' : CategoryId,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), CategoryId, IDL.Bool],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [CategoryId],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markOrderAsPaid' : IDL.Func([OrderId], [], []),
  'placeOrder' : IDL.Func(
      [IDL.Vec(CartItem), CustomerDetails, PaymentMethod],
      [OrderId],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedDemoData' : IDL.Func([], [], []),
  'trackOrder' : IDL.Func([OrderId, IDL.Text], [IDL.Opt(Order)], ['query']),
  'updateCategory' : IDL.Func([CategoryId, IDL.Text, IDL.Text], [], []),
  'updatePaymentStatus' : IDL.Func([OrderId, PaymentStatus], [], []),
  'updateProduct' : IDL.Func(
      [
        ProductId,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        CategoryId,
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CategoryId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'failed' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Record({ 'upiId' : IDL.Text }),
    'cashOnDelivery' : IDL.Null,
  });
  const OrderId = IDL.Nat;
  const ProductId = IDL.Nat;
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const CustomerDetails = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'pinCode' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Order = IDL.Record({
    'paymentStatus' : PaymentStatus,
    'paymentMethod' : PaymentMethod,
    'orderId' : OrderId,
    'cartItems' : IDL.Vec(CartItem),
    'totalAmount' : IDL.Nat,
    'customerDetails' : CustomerDetails,
  });
  const Product = IDL.Record({
    'categoryId' : CategoryId,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'productId' : ProductId,
    'imageUrl' : IDL.Opt(IDL.Text),
    'price' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'city' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'state' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'pinCode' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const Category = IDL.Record({
    'categoryId' : CategoryId,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), CategoryId, IDL.Bool],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markOrderAsPaid' : IDL.Func([OrderId], [], []),
    'placeOrder' : IDL.Func(
        [IDL.Vec(CartItem), CustomerDetails, PaymentMethod],
        [OrderId],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedDemoData' : IDL.Func([], [], []),
    'trackOrder' : IDL.Func([OrderId, IDL.Text], [IDL.Opt(Order)], ['query']),
    'updateCategory' : IDL.Func([CategoryId, IDL.Text, IDL.Text], [], []),
    'updatePaymentStatus' : IDL.Func([OrderId, PaymentStatus], [], []),
    'updateProduct' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          CategoryId,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };